provider: libvirt
machines:
    -   role: master
        name: master
        box: generic/ubuntu2010
        memory: 6000  # in bytes
        cpu: 2
        ip: 192.168.121.10
    -   role: worker
        name: worker
        box: generic/ubuntu2010
        memory: 6000  # in bytes
        cpu: 2

